name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc texlive

      - name: Generate PDF
        run: |
          tools/prepare_md.py --oss | pandoc -f markdown+smart --pdf-engine=xelatex -H tools/header.tex tools/default.yaml - -V date="$(date "+%e %B %Y")" -o changelog-oss.pdf
          ls -l changelog-oss.pdf