name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"

      - name: Install dependencies
        run: |
          apt update && apt install -y pandoc

      - name: Generate PDF
        run: |
          tools/prepare_md.py | pandoc --format markdown --pdf-engine=xelatex -H header.tex default.yaml - -V date=$(date "+%e %B %Y") -o changelog.pdf
